//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.26 at 08:51:35 odp. CET 
//


package cz.cvut.hnatuluk.entities.docxTemplate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}label"/>
 *         &lt;element ref="{}relationCardinalityEndFrom"/>
 *         &lt;element ref="{}relationCardinalityStartFrom"/>
 *         &lt;element ref="{}relationCardinalityStartTo"/>
 *         &lt;element ref="{}relationFromClassname"/>
 *         &lt;element ref="{}relationToClassname"/>
 *         &lt;element ref="{}relationType"/>
 *         &lt;element ref="{}relationCardinalityEndTo"/>
 *       &lt;/all>
 *       &lt;attribute name="style" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "relation")
public class Relation {

    @XmlElement(required = true)
    protected Label label;
    @XmlElement(required = true)
    protected RelationCardinalityEndFrom relationCardinalityEndFrom;
    @XmlElement(required = true)
    protected RelationCardinalityStartFrom relationCardinalityStartFrom;
    @XmlElement(required = true)
    protected RelationCardinalityStartTo relationCardinalityStartTo;
    @XmlElement(required = true)
    protected RelationFromClassname relationFromClassname;
    @XmlElement(required = true)
    protected RelationToClassname relationToClassname;
    @XmlElement(required = true)
    protected RelationType relationType;
    @XmlElement(required = true)
    protected RelationCardinalityEndTo relationCardinalityEndTo;
    @XmlAttribute(name = "style")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String style;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setLabel(Label value) {
        this.label = value;
    }

    /**
     * Gets the value of the relationCardinalityEndFrom property.
     * 
     * @return
     *     possible object is
     *     {@link RelationCardinalityEndFrom }
     *     
     */
    public RelationCardinalityEndFrom getRelationCardinalityEndFrom() {
        return relationCardinalityEndFrom;
    }

    /**
     * Sets the value of the relationCardinalityEndFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationCardinalityEndFrom }
     *     
     */
    public void setRelationCardinalityEndFrom(RelationCardinalityEndFrom value) {
        this.relationCardinalityEndFrom = value;
    }

    /**
     * Gets the value of the relationCardinalityStartFrom property.
     * 
     * @return
     *     possible object is
     *     {@link RelationCardinalityStartFrom }
     *     
     */
    public RelationCardinalityStartFrom getRelationCardinalityStartFrom() {
        return relationCardinalityStartFrom;
    }

    /**
     * Sets the value of the relationCardinalityStartFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationCardinalityStartFrom }
     *     
     */
    public void setRelationCardinalityStartFrom(RelationCardinalityStartFrom value) {
        this.relationCardinalityStartFrom = value;
    }

    /**
     * Gets the value of the relationCardinalityStartTo property.
     * 
     * @return
     *     possible object is
     *     {@link RelationCardinalityStartTo }
     *     
     */
    public RelationCardinalityStartTo getRelationCardinalityStartTo() {
        return relationCardinalityStartTo;
    }

    /**
     * Sets the value of the relationCardinalityStartTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationCardinalityStartTo }
     *     
     */
    public void setRelationCardinalityStartTo(RelationCardinalityStartTo value) {
        this.relationCardinalityStartTo = value;
    }

    /**
     * Gets the value of the relationFromClassname property.
     * 
     * @return
     *     possible object is
     *     {@link RelationFromClassname }
     *     
     */
    public RelationFromClassname getRelationFromClassname() {
        return relationFromClassname;
    }

    /**
     * Sets the value of the relationFromClassname property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationFromClassname }
     *     
     */
    public void setRelationFromClassname(RelationFromClassname value) {
        this.relationFromClassname = value;
    }

    /**
     * Gets the value of the relationToClassname property.
     * 
     * @return
     *     possible object is
     *     {@link RelationToClassname }
     *     
     */
    public RelationToClassname getRelationToClassname() {
        return relationToClassname;
    }

    /**
     * Sets the value of the relationToClassname property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationToClassname }
     *     
     */
    public void setRelationToClassname(RelationToClassname value) {
        this.relationToClassname = value;
    }

    /**
     * Gets the value of the relationType property.
     * 
     * @return
     *     possible object is
     *     {@link RelationType }
     *     
     */
    public RelationType getRelationType() {
        return relationType;
    }

    /**
     * Sets the value of the relationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationType }
     *     
     */
    public void setRelationType(RelationType value) {
        this.relationType = value;
    }

    /**
     * Gets the value of the relationCardinalityEndTo property.
     * 
     * @return
     *     possible object is
     *     {@link RelationCardinalityEndTo }
     *     
     */
    public RelationCardinalityEndTo getRelationCardinalityEndTo() {
        return relationCardinalityEndTo;
    }

    /**
     * Sets the value of the relationCardinalityEndTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationCardinalityEndTo }
     *     
     */
    public void setRelationCardinalityEndTo(RelationCardinalityEndTo value) {
        this.relationCardinalityEndTo = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStyle(String value) {
        this.style = value;
    }

}
