//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.26 at 08:51:37 odp. CET 
//


package cz.cvut.hnatuluk.entities.style;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}family"/>
 *         &lt;element ref="{}size"/>
 *         &lt;element ref="{}bold"/>
 *         &lt;element ref="{}italics"/>
 *         &lt;element ref="{}underline"/>
 *         &lt;element ref="{}strike"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "font")
public class Font {

    @XmlElement(required = true)
    protected String family;
    @XmlElement(required = true)
    protected BigInteger size;
    @XmlElement(required = true)
    protected Bold bold;
    @XmlElement(required = true)
    protected Italics italics;
    @XmlElement(required = true)
    protected Underline underline;
    @XmlElement(required = true)
    protected Strike strike;

    /**
     * Gets the value of the family property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamily() {
        return family;
    }

    /**
     * Sets the value of the family property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamily(String value) {
        this.family = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSize(BigInteger value) {
        this.size = value;
    }

    /**
     * Gets the value of the bold property.
     * 
     * @return
     *     possible object is
     *     {@link Bold }
     *     
     */
    public Bold getBold() {
        return bold;
    }

    /**
     * Sets the value of the bold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bold }
     *     
     */
    public void setBold(Bold value) {
        this.bold = value;
    }

    /**
     * Gets the value of the italics property.
     * 
     * @return
     *     possible object is
     *     {@link Italics }
     *     
     */
    public Italics getItalics() {
        return italics;
    }

    /**
     * Sets the value of the italics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Italics }
     *     
     */
    public void setItalics(Italics value) {
        this.italics = value;
    }

    /**
     * Gets the value of the underline property.
     * 
     * @return
     *     possible object is
     *     {@link Underline }
     *     
     */
    public Underline getUnderline() {
        return underline;
    }

    /**
     * Sets the value of the underline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Underline }
     *     
     */
    public void setUnderline(Underline value) {
        this.underline = value;
    }

    /**
     * Gets the value of the strike property.
     * 
     * @return
     *     possible object is
     *     {@link Strike }
     *     
     */
    public Strike getStrike() {
        return strike;
    }

    /**
     * Sets the value of the strike property.
     * 
     * @param value
     *     allowed object is
     *     {@link Strike }
     *     
     */
    public void setStrike(Strike value) {
        this.strike = value;
    }

}
