//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.13 at 07:55:02 odp. CET 
//


package cz.cvut.hnatuluk.epim.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.w3schools.com}heading"/>
 *         &lt;element ref="{http://www.w3schools.com}attrName"/>
 *         &lt;element ref="{http://www.w3schools.com}attrDataType"/>
 *         &lt;element ref="{http://www.w3schools.com}attrVisibility"/>
 *         &lt;element ref="{http://www.w3schools.com}anotationList"/>
 *         &lt;element ref="{http://www.w3schools.com}staticText"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "attribute")
public class Attribute {

    @XmlElement(required = true)
    protected Heading heading;
    @XmlElement(required = true)
    protected AttrName attrName;
    @XmlElement(required = true)
    protected AttrDataType attrDataType;
    @XmlElement(required = true)
    protected AttrVisibility attrVisibility;
    @XmlElement(required = true)
    protected AnotationList anotationList;
    @XmlElement(required = true)
    protected StaticText staticText;

    /**
     * Gets the value of the heading property.
     * 
     * @return
     *     possible object is
     *     {@link Heading }
     *     
     */
    public Heading getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Heading }
     *     
     */
    public void setHeading(Heading value) {
        this.heading = value;
    }

    /**
     * Gets the value of the attrName property.
     * 
     * @return
     *     possible object is
     *     {@link AttrName }
     *     
     */
    public AttrName getAttrName() {
        return attrName;
    }

    /**
     * Sets the value of the attrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttrName }
     *     
     */
    public void setAttrName(AttrName value) {
        this.attrName = value;
    }

    /**
     * Gets the value of the attrDataType property.
     * 
     * @return
     *     possible object is
     *     {@link AttrDataType }
     *     
     */
    public AttrDataType getAttrDataType() {
        return attrDataType;
    }

    /**
     * Sets the value of the attrDataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttrDataType }
     *     
     */
    public void setAttrDataType(AttrDataType value) {
        this.attrDataType = value;
    }

    /**
     * Gets the value of the attrVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link AttrVisibility }
     *     
     */
    public AttrVisibility getAttrVisibility() {
        return attrVisibility;
    }

    /**
     * Sets the value of the attrVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttrVisibility }
     *     
     */
    public void setAttrVisibility(AttrVisibility value) {
        this.attrVisibility = value;
    }

    /**
     * Gets the value of the anotationList property.
     * 
     * @return
     *     possible object is
     *     {@link AnotationList }
     *     
     */
    public AnotationList getAnotationList() {
        return anotationList;
    }

    /**
     * Sets the value of the anotationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnotationList }
     *     
     */
    public void setAnotationList(AnotationList value) {
        this.anotationList = value;
    }

    /**
     * Gets the value of the staticText property.
     * 
     * @return
     *     possible object is
     *     {@link StaticText }
     *     
     */
    public StaticText getStaticText() {
        return staticText;
    }

    /**
     * Sets the value of the staticText property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticText }
     *     
     */
    public void setStaticText(StaticText value) {
        this.staticText = value;
    }

}
