//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.13 at 07:55:02 odp. CET 
//


package cz.cvut.hnatuluk.epim.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.w3schools.com}heading"/>
 *         &lt;element ref="{http://www.w3schools.com}className"/>
 *         &lt;element ref="{http://www.w3schools.com}classVisibility"/>
 *         &lt;element ref="{http://www.w3schools.com}attrList"/>
 *         &lt;element ref="{http://www.w3schools.com}methodList"/>
 *         &lt;element ref="{http://www.w3schools.com}anotationList"/>
 *         &lt;element ref="{http://www.w3schools.com}relationList"/>
 *         &lt;element ref="{http://www.w3schools.com}staticText"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "class")
public class Class {

    @XmlElement(required = true)
    protected Heading heading;
    @XmlElement(required = true)
    protected ClassName className;
    @XmlElement(required = true)
    protected ClassVisibility classVisibility;
    @XmlElement(required = true)
    protected AttrList attrList;
    @XmlElement(required = true)
    protected MethodList methodList;
    @XmlElement(required = true)
    protected AnotationList anotationList;
    @XmlElement(required = true)
    protected RelationList relationList;
    @XmlElement(required = true)
    protected StaticText staticText;

    /**
     * Gets the value of the heading property.
     * 
     * @return
     *     possible object is
     *     {@link Heading }
     *     
     */
    public Heading getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Heading }
     *     
     */
    public void setHeading(Heading value) {
        this.heading = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link ClassName }
     *     
     */
    public ClassName getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassName }
     *     
     */
    public void setClassName(ClassName value) {
        this.className = value;
    }

    /**
     * Gets the value of the classVisibility property.
     * 
     * @return
     *     possible object is
     *     {@link ClassVisibility }
     *     
     */
    public ClassVisibility getClassVisibility() {
        return classVisibility;
    }

    /**
     * Sets the value of the classVisibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassVisibility }
     *     
     */
    public void setClassVisibility(ClassVisibility value) {
        this.classVisibility = value;
    }

    /**
     * Gets the value of the attrList property.
     * 
     * @return
     *     possible object is
     *     {@link AttrList }
     *     
     */
    public AttrList getAttrList() {
        return attrList;
    }

    /**
     * Sets the value of the attrList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttrList }
     *     
     */
    public void setAttrList(AttrList value) {
        this.attrList = value;
    }

    /**
     * Gets the value of the methodList property.
     * 
     * @return
     *     possible object is
     *     {@link MethodList }
     *     
     */
    public MethodList getMethodList() {
        return methodList;
    }

    /**
     * Sets the value of the methodList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MethodList }
     *     
     */
    public void setMethodList(MethodList value) {
        this.methodList = value;
    }

    /**
     * Gets the value of the anotationList property.
     * 
     * @return
     *     possible object is
     *     {@link AnotationList }
     *     
     */
    public AnotationList getAnotationList() {
        return anotationList;
    }

    /**
     * Sets the value of the anotationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnotationList }
     *     
     */
    public void setAnotationList(AnotationList value) {
        this.anotationList = value;
    }

    /**
     * Gets the value of the relationList property.
     * 
     * @return
     *     possible object is
     *     {@link RelationList }
     *     
     */
    public RelationList getRelationList() {
        return relationList;
    }

    /**
     * Sets the value of the relationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationList }
     *     
     */
    public void setRelationList(RelationList value) {
        this.relationList = value;
    }

    /**
     * Gets the value of the staticText property.
     * 
     * @return
     *     possible object is
     *     {@link StaticText }
     *     
     */
    public StaticText getStaticText() {
        return staticText;
    }

    /**
     * Sets the value of the staticText property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticText }
     *     
     */
    public void setStaticText(StaticText value) {
        this.staticText = value;
    }

}
