//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.13 at 07:55:02 odp. CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3schools.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cz.cvut.hnatuluk.epim.schemas;
