//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.13 at 07:55:02 odp. CET 
//


package cz.cvut.hnatuluk.epim.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.w3schools.com}heading"/>
 *         &lt;element ref="{http://www.w3schools.com}relationFromClassName"/>
 *         &lt;element ref="{http://www.w3schools.com}relationToClassName"/>
 *         &lt;element ref="{http://www.w3schools.com}relationType"/>
 *         &lt;element ref="{http://www.w3schools.com}relationCardinalityFrom"/>
 *         &lt;element ref="{http://www.w3schools.com}relationCardinalityTo"/>
 *         &lt;element ref="{http://www.w3schools.com}staticText"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "relation")
public class Relation {

    @XmlElement(required = true)
    protected Heading heading;
    @XmlElement(required = true)
    protected RelationFromClassName relationFromClassName;
    @XmlElement(required = true)
    protected RelationToClassName relationToClassName;
    @XmlElement(required = true)
    protected RelationType relationType;
    @XmlElement(required = true)
    protected Object relationCardinalityFrom;
    @XmlElement(required = true)
    protected Object relationCardinalityTo;
    @XmlElement(required = true)
    protected StaticText staticText;

    /**
     * Gets the value of the heading property.
     * 
     * @return
     *     possible object is
     *     {@link Heading }
     *     
     */
    public Heading getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Heading }
     *     
     */
    public void setHeading(Heading value) {
        this.heading = value;
    }

    /**
     * Gets the value of the relationFromClassName property.
     * 
     * @return
     *     possible object is
     *     {@link RelationFromClassName }
     *     
     */
    public RelationFromClassName getRelationFromClassName() {
        return relationFromClassName;
    }

    /**
     * Sets the value of the relationFromClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationFromClassName }
     *     
     */
    public void setRelationFromClassName(RelationFromClassName value) {
        this.relationFromClassName = value;
    }

    /**
     * Gets the value of the relationToClassName property.
     * 
     * @return
     *     possible object is
     *     {@link RelationToClassName }
     *     
     */
    public RelationToClassName getRelationToClassName() {
        return relationToClassName;
    }

    /**
     * Sets the value of the relationToClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationToClassName }
     *     
     */
    public void setRelationToClassName(RelationToClassName value) {
        this.relationToClassName = value;
    }

    /**
     * Gets the value of the relationType property.
     * 
     * @return
     *     possible object is
     *     {@link RelationType }
     *     
     */
    public RelationType getRelationType() {
        return relationType;
    }

    /**
     * Sets the value of the relationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationType }
     *     
     */
    public void setRelationType(RelationType value) {
        this.relationType = value;
    }

    /**
     * Gets the value of the relationCardinalityFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRelationCardinalityFrom() {
        return relationCardinalityFrom;
    }

    /**
     * Sets the value of the relationCardinalityFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRelationCardinalityFrom(Object value) {
        this.relationCardinalityFrom = value;
    }

    /**
     * Gets the value of the relationCardinalityTo property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRelationCardinalityTo() {
        return relationCardinalityTo;
    }

    /**
     * Sets the value of the relationCardinalityTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRelationCardinalityTo(Object value) {
        this.relationCardinalityTo = value;
    }

    /**
     * Gets the value of the staticText property.
     * 
     * @return
     *     possible object is
     *     {@link StaticText }
     *     
     */
    public StaticText getStaticText() {
        return staticText;
    }

    /**
     * Sets the value of the staticText property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticText }
     *     
     */
    public void setStaticText(StaticText value) {
        this.staticText = value;
    }

}
